name: Build Android 5.0 (API 21) 32-bit APK

on:
  push:
    branches: [ main ]
  workflow_dispatch:   # 手动触发按钮
defaults:
  run:
    working-directory: app1
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # 1. 检出源码
    - name: Checkout
      uses: actions/checkout@v4

    # 2. 配置 JDK 8（Android 5 编译链必须）
    - name: Set up JDK 8
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '8'

    # 3. 缓存 Gradle 依赖 & 构建缓存，加速后续运行
    - name: Cache Gradle
      uses: actions/cache@v4
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: |
          ${{ runner.os }}-gradle-

    # 4. 创建 local.properties（CI 里不写密钥，仅占位）
    - name: Create local.properties
      run: touch local.properties

    # 5. 赋予 Gradle 可执行权限（Linux  runner 需要）
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    # 6. 编译 Release APK（自动使用 build.gradle.kts 里的签名配置）
    - name: Build Release APK
      run: ./gradlew assembleRelease --stacktrace

    # 7. 上传 APK 到 Actions 构建产物，保留 90 天
    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: everytalk-android5-32bit-release
        path: app/build/outputs/apk/release/*.apk
        retention-days: 90
