name: Build Android 32-bit APK for Android 5+

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Java
      uses: actions/setup-java@v3
      with:
        distribution: 'zulu'
        java-version: '11'

    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.13.9' # 使用一个支持Android 5的Flutter版本
        channel: 'stable'

    - name: Install dependencies
      run: flutter pub get

    - name: Verify Android SDK components
      run: |
        echo "y" | sdkmanager "platforms;android-21" # Android 5.0 (API 21)
        echo "y" | sdkmanager "build-tools;30.0.3"

    - name: Build APK for armeabi-v7a (32-bit)
      run: |
        flutter build apk --release --target-platform=android-arm
        
    - name: Upload APK artifact
      uses: actions/upload-artifact@v3
      with:
        name: app-arm32-release
        path: build/app/outputs/flutter-apk/app-release.apk